import { RealtyObject, RealtyType } from './types';

export const realtyData: RealtyObject[] = [
  {
    type: RealtyType.HOUSE,
    cost: 22000000,
    costPerMeter: 99099,
    rooms: 5,
    area: 222,
    floorTotal: 2,
    address: 'Московская обл., Ленинский г.о., Видное, Хуторская ул., 16',
    images: [
      '/realty-cards/1/1.jpeg',
      '/realty-cards/1/2.jpeg',
      '/realty-cards/1/3.jpeg',
      '/realty-cards/1/4.jpeg',
      '/realty-cards/1/5.jpeg',
    ],
  },
  {
    type: RealtyType.FLAT,
    cost: 4650000,
    costPerMeter: 99572,
    rooms: 2,
    area: 46.7,
    floor: 4,
    floorTotal: 5,
    address: 'Московская обл., Орехово-Зуевский г.о., Орехово-Зуево, пр. Бондаренко, 6',
    images: [
      '/realty-cards/2/1.jpeg',
      '/realty-cards/2/2.jpeg',
      '/realty-cards/2/3.jpeg',
      '/realty-cards/2/4.jpeg',
      '/realty-cards/2/5.jpeg',
    ],
  },
  {
    type: RealtyType.HOUSE,
    cost: 20500000,
    costPerMeter: 66129,
    rooms: 5,
    area: 310,
    floorTotal: 2,
    address:
      'Московская обл., Орехово-Зуевский г.о., Орехово-Зуево, Народная ул. Горьковское шоссе, 70 км',
    images: [
      '/realty-cards/3/1.jpeg',
      '/realty-cards/3/2.jpeg',
      '/realty-cards/3/3.jpeg',
      '/realty-cards/3/4.jpeg',
      '/realty-cards/3/5.jpeg',
    ],
  },
  {
    type: RealtyType.FLAT,
    cost: 19500000,
    costPerMeter: 229412,
    rooms: 3,
    area: 85,
    floor: 7,
    floorTotal: 10,
    address: 'Москва, Оренбургская ул., 3',
    images: [
      '/realty-cards/4/1.jpeg',
      '/realty-cards/4/2.jpeg',
      '/realty-cards/4/3.jpeg',
      '/realty-cards/4/4.jpeg',
      '/realty-cards/4/5.jpeg',
    ],
  },
  {
    type: RealtyType.HOUSE,
    cost: 19800000,
    costPerMeter: 123750,
    rooms: 6,
    area: 160,
    floorTotal: 1,
    address: 'Московская обл., г.о. Ступино, Приозёрная ул., 41В',
    images: [
      '/realty-cards/5/1.jpeg',
      '/realty-cards/5/2.jpeg',
      '/realty-cards/5/3.jpeg',
      '/realty-cards/5/4.jpeg',
      '/realty-cards/5/5.jpeg',
    ],
  },
  {
    type: RealtyType.FLAT,
    cost: 6700000,
    costPerMeter: 83437,
    rooms: 3,
    area: 80.3,
    floor: 1,
    floorTotal: 4,
    address: 'Московская обл., г. Орехово-Зуево на ул. Гагарина д. 7',
    images: [
      '/realty-cards/6/1.jpeg',
      '/realty-cards/6/2.jpeg',
      '/realty-cards/6/3.jpeg',
      '/realty-cards/6/4.jpeg',
      '/realty-cards/6/5.jpeg',
    ],
  },
];
